#	$Id: Makefile.linux,v 1.3 2000/05/11 20:06:59 claudio Exp $
IMODULES = im_bsd.o im_udp.o im_unix.o
OMODULES = om_classic.o peo/om_peo.o
OBJS = syslogd.o modules.o ttymsg.o iolib.o peo/hash.o peo/md5c.o peo/rmd160.o peo/sha1.o $(IMODULES) $(OMODULES)

all: syslogd

syslogd: $(OBJS)

clean:
	rm -f *.o syslogd
