.\"	$CoreSDI: im_udp.8,v 1.6 2001/11/06 23:08:53 alejo Exp $
.\"
.\" Copyright (c) 2000, 2001
.\"	Core-SDI SA. All rights reserved.
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. Neither the name of Core-SDI SA nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\"
.Dd Apr 05, 2001
.Dt IM_UDP 8
.Os Core-SDI
.Sh NAME
.Nm UDP input module
.Nd
.Xr syslogd 8
input module for UDP network logging
.Sh SYNOPSIS
.Nm udp
.Op Fl a
.Op Fl q
.Op Fl h Ar host
.Op Fl p Ar port
.Sh DESCRIPTION
Listens on an UDP port for incoming log messages for the
.Xr syslogd 8
daemon.
.Sh EXAMPLES
.Bl -bullet
.It
The following command starts the
.Xr syslogd 8
daemon and logs UDP logging information coming in on the default port only:
.Pp
.Dl syslogd -i udp
.Pp
.It
This does the same as above, but listens on address local.example.com
port 1777 instead:
.Pp
.Dl syslogd -i udp '-h local.example.com -p 1777'
.El
.Pp
.Bl -bullet
.It
This does the same as above, but gets host name from message:
.Pp
.Dl syslogd -i udp '-a -h local.example.com -p 1777'
.El
.Bl -bullet
.It
The following is the same, but avoids adding full fomain (FQDN):
.Pp
.Dl syslogd -i 'udp -q -a -h local.example.com -p 1777'
.Pp
.Sh SEE ALSO
.Xr syslog 3 ,
.Xr im_bsd 8 ,
.Xr im_doors 8 ,
.Xr im_linux 8 ,
.Xr im_streams 8 ,
.Xr im_tcp 8 ,
.Xr im_unix 8 ,
.Xr syslogd 8
.Sh BUGS
.Bl -bullet
.It
Submit bugs at this project's Sourceforge Bug reporting system at:    
http://sourceforge.net/tracker/?func=add&group_id=25741&atid=385117
You may also report them directly to the authors; send an email to
core.devel.alat@corest.com, describing the problem the most you can,
containing also machine description, hardware description, the
configuration file (/etc/syslog.conf), the OS description, and the
invoking command line.
The more you describe the bug, the faster we can fix it.
.El
